# Generated by Django 4.2.20 on 2025-03-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': ('Tipo de Veículo',),
                'verbose_name_plural': 'Tipos de Veiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer', verbose_name='Propietário')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype', verbose_name='Tipo Do Veículo')),
            ],
            options={
                'verbose_name': ('Veículo',),
                'verbose_name_plural': 'Veiculos',
            },
        ),
    ]
